// Writes the docs page "Solana ZEC holders" from the dated snapshots in docs/stats-*.json, so every
// figure on it comes from a committed file made by solana-zec-holders.mjs. Not live: a row is added
// when the script is run again and its output committed.
// Usage: node scripts/stats/holders-page.mjs          (writes the page)
//        node scripts/stats/holders-page.mjs --check  (fails if the page is out of date; run by the site build)

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join(import.meta.dirname, '../..');
const OUT = path.join(ROOT, 'apps/docs/content/docs/holders.mdx');
const REPO = 'https://github.com/ZecDoor/zecdoor/blob/main';

const files = fs
  .readdirSync(path.join(ROOT, 'docs'))
  .filter((f) => /^stats-\d{4}-\d{2}-\d{2}\.json$/.test(f))
  .sort();
const snaps = files.map((f) => ({ file: f, ...JSON.parse(fs.readFileSync(path.join(ROOT, 'docs', f), 'utf8')) }));
const tiered = snaps.filter((s) => s.above);
const latest = tiered.at(-1);
if (!latest) throw new Error('no tiered snapshot in docs/');

const n = (v) => Number(v).toLocaleString('en-US');
const z = (v, d = 2) => Number(v).toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d });
const when = (iso) => {
  const d = new Date(iso);
  return `${d.getUTCDate()} ${d.toLocaleString('en-GB', { month: 'short', timeZone: 'UTC' })} ${d.getUTCFullYear()}, ${String(d.getUTCHours()).padStart(2, '0')}:${String(d.getUTCMinutes()).padStart(2, '0')} UTC`;
};
const day = (iso) => when(iso).split(',')[0];
const zat = (v) => (Number(v) / 1e8).toFixed(8).replace(/0+$/, '');
const link = (f) => `[\`docs/${f}\`](${REPO}/docs/${f})`;
const file = (f) => `[JSON](${REPO}/docs/${f})`;

const tiers = [
  ['above', 'At or above the bridge minimum', 'a plain move'],
  ['belowButWorthMoving', 'Below the minimum, worth moving', 'the top-up'],
  ['dust', 'Dust, worth less than a move costs', 'not worth moving'],
];

const bar = (share, tone) =>
  `<div style={{ height: 10, borderRadius: 5, background: 'var(--color-fd-muted)', overflow: 'hidden' }}><div style={{ width: '${share}', height: '100%', background: '${tone}' }} /></div>`;
const TONES = { above: 'var(--color-fd-primary)', belowButWorthMoving: 'color-mix(in oklab, var(--color-fd-primary) 55%, transparent)', dust: 'var(--color-fd-muted-foreground)' };

const L = latest;
const page = `---
title: Solana ZEC holders
description: Dated snapshots of every Solana account holding bridged ZEC, in three tiers, with their sources. Not live.
---

{/* Generated by scripts/stats/holders-page.mjs from docs/stats-*.json. Do not edit by hand. */}

Every SPL token account holding bridged ZEC (mint \`A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS\`), counted from chain
state and sorted by whether moving it to a shielded Zcash wallet is worth it. **These are dated snapshots, not live
figures:** each one is a run of [\`scripts/stats/solana-zec-holders.mjs\`](${REPO}/scripts/stats/solana-zec-holders.mjs)
committed with its date. Token accounts are not people: one person can hold several, exchanges hold many users' balances
in one, and pools are programs.

## Latest: ${when(L.at)}

${n(L.nonEmpty)} accounts held ${z(L.zecTotal)} ZEC. Source: ${link(L.file)}.

${tiers
  .map(
    ([k, label, what]) => `<div style={{ display: 'grid', gap: 6, margin: '18px 0' }}>
  <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><strong>${label}</strong><span>${n(L[k].accounts)} accounts · ${L.shares[k]} · ${z(L[k].zec)} ZEC</span></div>
  ${bar(L.shares[k], TONES[k])}
  <span style={{ fontSize: 14, opacity: 0.75 }}>${what}</span>
</div>`,
  )
  .join('\n\n')}

The bars are shares of accounts. By ZEC held, the first tier has ${((Number(L.above.zec) / Number(L.zecTotal)) * 100).toFixed(2)}%.

| Tier | Accounts | ZEC | Owned by a wallet | Owned by a program or pool |
|---|---|---|---|---|
${tiers.map(([k, label]) => `| ${label} | ${n(L[k].accounts)} | ${z(L[k].zec)} | ${n(L[k].walletOwned.accounts)} (${z(L[k].walletOwned.zec)} ZEC) | ${n(L[k].programOwned.accounts)} (${z(L[k].programOwned.zec)} ZEC) |`).join('\n')}
| **All non-empty accounts** | **${n(L.nonEmpty)}** | **${z(L.zecTotal)}** | | |

### Where the lines are

- **Bridge minimum:** ${zat(L.bridgeMinimumZat)} ZEC, from a NEAR Intents dry quote at the time.
- **Worth moving from:** ${zat(L.worthMovingFromZat)} ZEC (about $${L.worthMovingFromUsd.toFixed(2)}), the fixed cost of one move: the bridge's payout
  fee as quoted (${n(L.fixedCostsZat.bridgePayoutFeeCeiling)} zat, a ceiling), the deposit account and Solana fee
  (${n(L.fixedCostsZat.depositAccountAndSolanaFee)} zat), our 0.25% of the minimum (${n(L.fixedCostsZat.ourFeeOnMinimum)} zat) and the top-up's 1% swap limit
  (${n(L.fixedCostsZat.topUpSlippageBound)} zat). The same formula decides when the app and [the wallet check](/check) say "not worth moving".
- **Prices:** $${z(L.prices.zecUsd)} per ZEC and $${z(L.prices.solUsd)} per SOL, NEAR Intents' token prices at the time.

## Every snapshot

| Taken | Non-empty accounts | At or above the minimum | Below, worth moving | Dust | ZEC held | Worth moving from | Source |
|---|---|---|---|---|---|---|---|
${snaps
  .slice()
  .reverse()
  .map((s) =>
    s.above
      ? `| ${when(s.at)} | ${n(s.nonEmpty)} | ${n(s.above.accounts)} | ${n(s.belowButWorthMoving.accounts)} | ${n(s.dust.accounts)} | ${z(s.zecTotal)} | ${zat(s.worthMovingFromZat)} ZEC ($${s.worthMovingFromUsd.toFixed(2)}) | ${file(s.file)} |`
      : `| ${when(s.at)} | ${n(s.nonEmpty)} | ${n(s.nonEmpty - s.belowMinimumWithFee)} | ${n(s.belowMinimumWithFee)} below the minimum, not separated | | ${z(s.zecTotal)} | not computed | ${file(s.file)} |`,
  )
  .join('\n')}

Changes between snapshots come from new accounts, transfers and price moves; the "worth moving" line moves with prices and
the bridge's terms. ${snaps.length} snapshots so far, ${day(snaps[0].at)} to ${day(L.at)}.

## How each snapshot is taken

${(L.sources ? Object.entries(L.sources) : [])
  .map(([k, v]) => `- **${{ accounts: 'Accounts', minimumAndPayoutFee: 'Minimum and payout fee', prices: 'Prices', rent: 'Rent' }[k] ?? k}:** ${v.replace(/https:\/\/[^\s,]+/g, (u) => `\`${u}\``)}`)
  .join('\n')}
- Owners are told apart by whether the owner address is on the ed25519 curve (a wallet) or not (a program or pool).

To reproduce: \`node scripts/stats/solana-zec-holders.mjs https://api.mainnet-beta.solana.com > docs/stats-<date>.json\`
(the response is about 90 MB), then \`node scripts/stats/holders-page.mjs\` to rebuild this page. A live version would need a
server running the count on a schedule; we publish dated snapshots instead.
`;

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== page) {
    console.error('holders.mdx is out of date: run node scripts/stats/holders-page.mjs');
    process.exit(1);
  }
  console.log(`Holders page is current (${snaps.length} snapshots).`);
} else {
  fs.writeFileSync(OUT, page);
  console.log(`Wrote ${path.relative(ROOT, OUT)} from ${files.join(', ')}`);
}
